# Generated by Django 3.1.6 on 2021-09-18 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile/')),
                ('bio', models.TextField(blank=True, default='null')),
                ('interest', models.TextField(blank=True, default='null')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('prouser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('Published', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('banku', 'banku'), ('kenkey', 'kenkey'), ('rice', 'rice'), ('fufu', 'fufu'), ('burger', 'burger'), ('pizza', 'pizza')], max_length=50)),
                ('available', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='product', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-Published',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=250)),
                ('quantity', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('total_price', models.CharField(max_length=50)),
                ('Published', models.DateField(auto_now_add=True)),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('employee_name', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-Published',),
            },
        ),
    ]
