# Generated by Django 3.1.6 on 2021-09-18 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='create_time',
        ),
    ]
